// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1632274701);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1632274731);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 826);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("calendar.list.sortOrder", "4989c50e-2c10-4c56-b1c1-b6133984a70c");
user_pref("calendar.registry.4989c50e-2c10-4c56-b1c1-b6133984a70c.calendar-main-in-composite", true);
user_pref("calendar.registry.4989c50e-2c10-4c56-b1c1-b6133984a70c.disabled", true);
user_pref("calendar.registry.4989c50e-2c10-4c56-b1c1-b6133984a70c.name", "Home");
user_pref("calendar.registry.4989c50e-2c10-4c56-b1c1-b6133984a70c.type", "storage");
user_pref("calendar.registry.4989c50e-2c10-4c56-b1c1-b6133984a70c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Ho_Chi_Minh");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1632274682722");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210802223056");
user_pref("extensions.lastAppVersion", "78.13.0");
user_pref("extensions.lastPlatformVersion", "78.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"6f328b6a-14f7-47aa-88e6-6f01e0d687c3\",\"google@search.mozilla.org\":\"7f1a046e-99a0-407e-9789-ee661fb672a9\",\"amazondotcom@search.mozilla.org\":\"91356d75-0656-485d-9124-c21fa1f6273b\",\"bing@search.mozilla.org\":\"b5e1bb24-da05-42fd-90d7-0483a4bd4b13\",\"ddg@search.mozilla.org\":\"f135e4a4-52a3-46ab-be8a-6428dc08e9df\",\"wikipedia@search.mozilla.org\":\"62f9b0af-57e1-4d93-b6a2-d07814b196bb\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.provider.realname", "Nguyen Dinh Han");
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "7a0b4b51-3a9f-424d-8aa4-324342852fd");
user_pref("mailnews.filters.migration78", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "78.13.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "215a29e9-d102-4a47-bca4-06b2cf411410");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "c35c5f5c-d3ec-4b92-9e35-80e7f50eecda");
user_pref("toolkit.telemetry.previousBuildID", "20210802223056");
